basePath: /
definitions:
  models.Todo:
    properties:
      completed:
        example: false
        type: boolean
      id:
        example: 1
        type: integer
      title:
        example: 買い物に行く
        type: string
    type: object
host: go-todo-hh8n.onrender.com
info:
  contact: {}
  description: シンプルなTODO管理API
  title: TODO API
  version: "1.0"
paths:
  /todos:
    get:
      description: すべてのTODOを取得します
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Todo'
            type: array
      summary: TODO一覧取得
schemes:
- https
swagger: "2.0"
